### ISSUE TITLE
Manager​ ​kann​ ​Mitarbeiter​ ​anlegen​

### ISSUE THREAD

**Issue by querqueq** [sese-xp3-ws2017/sese-xp3-ws2017#45]
Als Manager kann man neue Mitarbeiter anlegen. Diesen wird eine der folgenden Rollen
zugewiesen: Manager, Stellvertreter, Rezeptionisten, Reinigungspersonal, Wartungstechniker.
Manager haben einsicht auf alles.
Rezeptionisten haben keine Einsicht auf die Urlaubsbestätigung und Arbeitsplanerstellung.
Wartungstechniker und Reinigungspersonal haben nur Einsicht auf die Reservierungs-,
Zimmer- und Mängelliste, Urlaubsantrag und Arbeitsplan.

**Comment by querqueq** [comment]
Aus dem Angebot übernommen.

Dieses Issue muss bearbeitet werden vor alle Issues, welche eine Beziehung zw. Manager und Mitarbeiter benötigen.

**Comment by querqueq** [comment]
### TODO for #38 #39 #45

* [ ] Database backed user authentication / Custom User Details Service
    1. [ ] Replace in memory authentication with database auth in SecurityConfig
    2. [ ] Implement CustomUserDetailsManager
    3. [ ] Set Password Encode to be BCryptPasswordEncoder to check passwords
* [ ] Request vacation view
* [ ] Resolve vacation requests view
* [ ] Add hint for default manager to login page
* [ ] Bootstrap login page
* [ ] Add test cases for request vacation that uses multiple vacations
* [ ] Set authorization for routes
* [ ] Release new version
